services:
  db:
    image: postgres:16
    container_name: technical_test_db
    environment:
      POSTGRES_DB: technical_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: technical_test_web
    # command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_ENGINE: postgresql
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: technical_test
      DB_USER: postgres
      DB_PASSWORD: postgres
      DJANGO_SETTINGS_MODULE: di_technical_test.settings
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: {}
