# Generated by Django 5.2.5 on 2025-08-17 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Companies",
            fields=[
                (
                    "id",
                    models.CharField(max_length=24, primary_key=True, serialize=False),
                ),
                ("company_name", models.CharField(max_length=130)),
                ("company_id", models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.CharField(max_length=24, primary_key=True, serialize=False),
                ),
                ("company_name", models.CharField(max_length=130)),
                ("company_id", models.CharField(max_length=24)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("status", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="Charges",
            fields=[
                (
                    "id",
                    models.CharField(max_length=24, primary_key=True, serialize=False),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("status", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.companies"
                    ),
                ),
            ],
        ),
    ]
