# Generated by Django 5.2.5 on 2025-08-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="company_id",
            field=models.CharField(max_length=40),
        ),
    ]
