# Generated by Django 5.2.5 on 2025-08-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_alter_sales_company_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companies",
            name="company_id",
        ),
        migrations.AlterField(
            model_name="companies",
            name="id",
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
