# Generated by Django 5.2.5 on 2025-08-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_remove_companies_company_id_alter_companies_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargeSummary",
            fields=[
                (
                    "id",
                    models.CharField(max_length=24, primary_key=True, serialize=False),
                ),
                ("company_name", models.CharField(max_length=130)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("status", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
            ],
            options={
                "db_table": "DAYLI_CHARGES",
                "managed": False,
            },
        ),
    ]
