# Generated by Django 5.2.5 on 2025-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_chargesummary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charges",
            name="id",
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sales",
            name="id",
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
