# Generated by Django 5.2.5 on 2025-08-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_alter_charges_id_alter_sales_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charges",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="sales",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
