# Generated by Django 5.2.5 on 2025-08-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_alter_charges_amount_alter_sales_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charges",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name="sales",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
