name: Docker Image CI-CD

on:
  [workflow_dispatch]
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t epalomeque/technical:$(date +%s)
    - name: Push to docker
      run: | 
        docker login -u epalomeque -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push epalomeque/technical:latest
